# Generated by Django 4.2.3 on 2023-07-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_page_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default='valor default do excerpt', max_length=150),
        ),
    ]
